module.exports = {
  variants: ['responsive'],
  utility: theme => ({
    '.hero-shadow-top': {
      pointerEvents: 'none',
      position: 'absolute',
      zIndex: theme('zIndex.active'),
      top: '0',
      bottom: 'auto',
      left: '0',
      right: 'auto',
      width: '100%',
      height: '100%',
      background: 'linear-gradient(0deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.3) 100%)',
    },
    '.hero-shadow-bottom': {
      pointerEvents: 'none',
      position: 'absolute',
      zIndex: theme('zIndex.active'),
      top: 'auto',
      left: '0',
      bottom: '0',
      right: 'auto',
      width: '100%',
      height: '100%',
      background: 'linear-gradient(180deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.3) 100%)',
    },
    '.hero-shadow-left': {
      pointerEvents: 'none',
      position: 'absolute',
      zIndex: theme('zIndex.active'),
      top: 'auto',
      left: '0',
      bottom: '0',
      right: 'auto',
      width: '100%',
      height: '100%',
      background: 'linear-gradient(-90deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.3) 100%)',
    },
    '.hero-shadow-right': {
      pointerEvents: 'none',
      position: 'absolute',
      zIndex: theme('zIndex.active'),
      top: 'auto',
      left: 'auto',
      bottom: '0',
      right: '0',
      width: '100%',
      height: '100%',
      background: 'linear-gradient(90deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.3) 100%)',
    },
  }),
}
