module.exports = {
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '1.5rem',
        sm: '2rem',
        md: '3rem',
        lg: '4rem',
        xl: '5rem',
      },
    },
    extend: {
      colors: {
        success: '#48bb78',
        error: '#f56565',
        accent: {
          50: '#F2F8FF',
          100: '#E6F2FF',
          200: '#BFDDFF',
          300: '#99C9FF',
          400: '#4DA1FF',
          500: '#0078FF',
          600: '#006CE6',
          700: '#004899',
          800: '#003673',
          900: '#00244D',
        },
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1.6' }],
        sm: ['0.875rem', { lineHeight: '1.6' }],
        base: ['1rem', { lineHeight: '1.6' }],
        lg: ['1.125rem', { lineHeight: '1.6' }],
        xl: ['1.25rem', { lineHeight: '1.5' }],
        '2xl': ['1.5rem', { lineHeight: '1.4' }],
        '3xl': ['1.875rem', { lineHeight: '1.3' }],
        '4xl': ['2.25rem', { lineHeight: '1.2' }],
        '5xl': ['3rem', { lineHeight: '1.1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        '7xl': ['4.5rem', { lineHeight: '1' }],
        '8xl': ['6rem', { lineHeight: '1' }],
        '9xl': ['8rem', { lineHeight: '1' }],
      },
      zIndex: {
        base: '0',
        active: '25',
        top: '50',
        backdrop: '500',
        drop: '600',
        sticky: '800', // same as javascript and decreses with sequential sticky
        overlay: '900',
        last: '1000',
      },
      inset: {
        100: '100%',
      },
      transitionTimingFunction: {
        ...require('./core/animation.css.js').transitionTimingFunction,
      },
      animation: {
        ...require('./core/animation.css.js').animation,
      },
      keyframes: theme => ({
        ...require('./core/animation.css.js').keyframes(theme),
      }),
    },
  },
  variants: {
    backgroundColor: ({ after }) => after(['group-active'], 'group-hover', after(['active'], 'hover')),
    gradientColorStops: ({ after }) => after(['group-active'], 'group-hover', after(['active'], 'hover')),
    backgroundOpacity: ({ after }) => after(['group-active'], 'group-hover', after(['active'], 'hover')),
    borderColor: ({ after }) => after(['group-active'], 'group-hover', after(['active'], 'hover')),
    borderOpacity: ({ after }) => after(['group-active'], 'group-hover', after(['active'], 'hover')),
    boxShadow: ({ after }) => after(['group-active'], 'group-hover', after(['active'], 'hover')),
    opacity: ({ after }) => after(['group-active'], 'group-hover', after(['active'], 'hover')),
    textColor: ({ after }) => after(['group-active'], 'group-hover', after(['active'], 'hover')),
    textOpacity: ({ after }) => after(['group-active'], 'group-hover', after(['active'], 'hover')),
    textDecoration: ({ after }) => after(['group-active'], 'group-hover', after(['active'], 'hover')),
    scale: ({ after }) => after(['group-active'], 'group-hover', after(['active'], 'hover')),
    rotate: ({ after }) => after(['group-active'], 'group-hover', after(['active'], 'hover')),
    translate: ({ after }) => after(['group-active'], 'group-hover', after(['active'], 'hover')),
    skew: ({ after }) => after(['group-active'], 'group-hover', after(['active'], 'hover')),
  },
  plugins: [require('./tailwind-plugin')],
}
