if (typeof window !== 'undefined') {
  require('xtend-library/src/addons/animation/mouse-follow.js')
  require('xtend-library/src/addons/animation/ripple-demo.js')
  require('xtend-library/src/addons/animation/ripple.js')
  require('xtend-library/src/addons/animation/scroll-to-anchor.js')
  require('xtend-library/src/addons/form/textarea-autosize-demo.js')
  require('xtend-library/src/addons/form/textarea-autosize.js')
  require('xtend-library/src/addons/global/jump-to-content.js')
  require('xtend-library/src/addons/group/group-expand.js')
  require('xtend-library/src/addons/group/group-number.js')
  require('xtend-library/src/addons/slider/navigation-sides.js')
  require('xtend-library/src/addons/test.js')
  require('xtend-library/src/addons/toggle/multilevel-demo.js')
  require('xtend-library/src/addons/toggle/multilevel.js')
}
